title: Hugo Story
theme: hugo-story
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
Params:
  description: A (modular, highly tweakable) responsive one-page theme for Hugo
  favicon: yes
  logo: images/banner.jpg
  social:
    email: caressofsteel@protonmail.com
    github: https://github.com/caressofsteel/
    instagram: https://instagram.com
    linkedin: https://linkedin.com
    telegram: https://telegram.org
    twitter: https://twitter.com/caressofsteel_
