baseurl: "https://tamararen.github.io"
title: Tamara Ren
theme: hugo-story
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
Params:
  description: PhD in Economics 
  favicon: yes
  logo: images/id.jpg
  social:
    email: tren@uoregon.edu
    github: https://github.com/tamararen/

